# Generated by Django 5.1.6 on 2025-03-11 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="post",
            options={},
        ),
    ]
